"""Resource table for the code generator: what the pinned schema cannot express.

Every result model names its response schema, its docstrings, and the field
rules the schema gets wrong or leaves out. The generator derives everything
else from the pinned OpenAPI document.
"""

from collections.abc import Mapping
from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class ModelSpec:
    """One result model and the field rules that override its schema.

    expand maps a linked field to the model it parses into when expanded.
    datetimes lists string fields that carry a timestamp without saying so.
    coerced lists string fields the API sometimes sends as a number.
    codes lists generated comma separated fields that parse into a tuple.
    nullable lists fields the schema marks required that arrive empty.
    """

    name: str
    schema: str
    doc: str
    nouns: tuple[str, str]
    expand: Mapping[str, str] = field(default_factory=dict)
    datetimes: tuple[str, ...] = ()
    coerced: tuple[str, ...] = ()
    codes: tuple[str, ...] = ()
    nullable: tuple[str, ...] = ()


MODELS: tuple[ModelSpec, ...] = (
    ModelSpec(
        name="Equipment",
        schema="EquipmentResponse",
        doc="One material: a rental or sales item tracked in inventory.",
        nouns=("equipment", "equipment"),
        expand={"folder": "Folder"},
        codes=("qrcodes", "qrcodes_of_serial_numbers", "tags"),
    ),
    ModelSpec(
        name="SerialNumber",
        schema="SerialNumberResponse",
        doc="One serialized unit of a material, the unit an RFID tag links to.",
        nouns=("serial number", "serial number"),
        expand={
            "equipment": "Equipment",
            "asset_location": "StockLocation",
            "last_subproject": "Subproject",
        },
        datetimes=("purchasedate", "next_inspection"),
        codes=("qrcodes", "tags"),
        nullable=("asset_location",),
    ),
    ModelSpec(
        name="EquipmentAssignedSerial",
        schema="EquipmentAssignedSerialsResponse",
        doc="One serial number placed inside a serialized combination.",
        nouns=("assigned serial", "assignment"),
        expand={"combination": "SerialNumber", "serialnumber": "SerialNumber"},
    ),
    ModelSpec(
        name="ActualContent",
        schema="ActualContentResponse",
        doc="One equipment item physically recorded inside a combination serial.",
        nouns=("actual content", "content"),
        expand={
            "equipment": "Equipment",
            "serial": "SerialNumber",
            "combination_serial": "SerialNumber",
        },
        coerced=("quantity",),
    ),
    ModelSpec(
        name="EquipmentSetContent",
        schema="EquipmentSetContentResponse",
        doc="One equipment line inside an equipment set combination.",
        nouns=("set content", "set content"),
        expand={"parent_equipment": "Equipment", "equipment": "Equipment"},
        coerced=("quantity", "order"),
    ),
    ModelSpec(
        name="Folder",
        schema="FolderResponse",
        doc="One folder that groups equipment items in the inventory tree.",
        nouns=("folder", "folder"),
        expand={"parent": "Folder"},
        coerced=("order",),
    ),
    ModelSpec(
        name="StockLocation",
        schema="StockLocationResponse",
        doc="One warehouse or storage location where stock is kept.",
        nouns=("stock location", "stock location"),
    ),
    ModelSpec(
        name="WarehouseStatus",
        schema="WarehouseStatusResponse",
        doc="One warehouse status that equipment can be booked to.",
        nouns=("warehouse status", "warehouse status"),
    ),
    ModelSpec(
        name="Status",
        schema="StatusResponse",
        doc="One planning status that a subproject can carry.",
        nouns=("status", "status"),
    ),
    ModelSpec(
        name="StockMovement",
        schema="StockMovementResponse",
        doc="One recorded change of stock for a material.",
        nouns=("stock movement", "stock movement"),
        expand={
            "equipment": "Equipment",
            "projectequipment": "ProjectEquipment",
            "stock_location": "StockLocation",
        },
    ),
    ModelSpec(
        name="Repair",
        schema="RepairResponse",
        doc="One repair of a material or of one of its serial numbers.",
        nouns=("repair", "repair"),
        expand={
            "equipment": "Equipment",
            "serialnumber": "SerialNumber",
            "subproject": "Subproject",
            "stock_location": "StockLocation",
            "unrepairable_of": "Repair",
        },
        codes=("tags",),
    ),
    ModelSpec(
        name="Project",
        schema="ProjectResponse",
        doc="One project that plans materials, crew, and transport.",
        nouns=("project", "project"),
        codes=("tags",),
        nullable=("project_type",),
    ),
    ModelSpec(
        name="Subproject",
        schema="SubprojectResponse",
        doc="One subproject inside a project, carrying its own planning period.",
        nouns=("subproject", "subproject"),
        expand={"project": "Project", "status": "Status", "asset_location_from": "StockLocation"},
        datetimes=("created", "modified"),
        coerced=("order",),
    ),
    ModelSpec(
        name="ProjectEquipment",
        schema="ProjectEquipmentResponse",
        doc="One planned equipment line on a project or subproject.",
        nouns=("project equipment", "planned equipment"),
        expand={"equipment": "Equipment", "parent": "ProjectEquipment"},
        datetimes=("created", "modified"),
        coerced=("quantity", "factor", "order"),
        nullable=("equipment_group",),
    ),
    ModelSpec(
        name="Accessory",
        schema="AccessoryResponse",
        doc="One material that planning adds together with its parent material.",
        nouns=("accessory", "accessory"),
        expand={"parent_equipment": "Equipment", "equipment": "Equipment"},
        coerced=("order",),
    ),
    ModelSpec(
        name="Alternative",
        schema="AlternativeResponse",
        doc="One material that can replace another material during planning.",
        nouns=("alternative", "alternative"),
        expand={"equipment": "Equipment", "alternative": "Equipment"},
    ),
    ModelSpec(
        name="Supplier",
        schema="SupplierResponse",
        doc="One purchase source of a material, priced through its contact.",
        nouns=("supplier", "supplier"),
        expand={"equipment": "Equipment"},
        nullable=("contact",),
    ),
    ModelSpec(
        name="Vehicle",
        schema="VehicleResponse",
        doc="One vehicle that planning books for transport.",
        nouns=("vehicle", "vehicle"),
        expand={"folder": "Folder", "asset_location": "StockLocation"},
        datetimes=("inspection_date",),
        codes=("tags",),
    ),
    ModelSpec(
        name="ExtraInputField",
        schema="ExtraInputFieldResponse",
        doc="One custom field definition attached to one item type.",
        nouns=("extra input field", "field definition"),
        expand={"parent": "ExtraInputField"},
        coerced=("order",),
    ),
    ModelSpec(
        name="ProjectStatus",
        schema="ProjectStatusResponse",
        doc="One status that a project can carry in the planning workflow.",
        nouns=("project status", "status"),
    ),
    ModelSpec(
        name="ProjectType",
        schema="ProjectTypeResponse",
        doc="One project type that groups projects by kind.",
        nouns=("project type", "type"),
    ),
    ModelSpec(
        name="ProjectFunctionGroup",
        schema="ProjectFunctionGroupResponse",
        doc="One group of functions inside a subproject plan.",
        nouns=("function group", "group"),
        expand={"project": "Project", "subproject": "Subproject"},
        datetimes=("created", "modified"),
    ),
    ModelSpec(
        name="ProjectFunction",
        schema="ProjectFunctionResponse",
        doc="One planned crew or transport function on a subproject.",
        nouns=("function", "planned function"),
        expand={"project": "Project", "subproject": "Subproject", "group": "ProjectFunctionGroup"},
        datetimes=("created", "modified", "recurrence_enddate"),
        coerced=("order",),
        codes=("tags",),
        nullable=("cost_rate", "price_rate"),
    ),
    ModelSpec(
        name="ProjectCrew",
        schema="ProjectCrewResponse",
        doc="One crew member planned on a project function.",
        nouns=("project crew", "crew planning"),
        expand={"function": "ProjectFunction"},
        datetimes=("created", "modified"),
    ),
    ModelSpec(
        name="ProjectVehicle",
        schema="ProjectVehicleResponse",
        doc="One vehicle planned on a project function.",
        nouns=("project vehicle", "transport planning"),
        expand={"function": "ProjectFunction", "vehicle": "Vehicle"},
        datetimes=("created", "modified"),
    ),
    ModelSpec(
        name="ProjectEquipmentGroup",
        schema="ProjectEquipmentGroupResponse",
        doc="One equipment group inside a subproject plan.",
        nouns=("equipment group", "group"),
        expand={"project": "Project", "subproject": "Subproject"},
        datetimes=("created", "modified"),
        coerced=("order",),
    ),
    ModelSpec(
        name="ProjectCost",
        schema="ProjectCostResponse",
        doc="One additional cost line on a subproject.",
        nouns=("project cost", "cost line"),
        expand={"project": "Project", "subproject": "Subproject"},
        datetimes=("created", "modified"),
        coerced=("order",),
    ),
    ModelSpec(
        name="ProjectRequest",
        schema="ProjectRequestResponse",
        doc="One equipment request submitted by a customer.",
        nouns=("project request", "request"),
        expand={"linked_project": "Project"},
    ),
    ModelSpec(
        name="ProjectRequestEquipment",
        schema="ProjectRequestEquipmentResponse",
        doc="One equipment line on a project request.",
        nouns=("request equipment", "requested line"),
        expand={
            "linked_equipment": "Equipment",
            "parent": "ProjectRequestEquipment",
            "project_request": "ProjectRequest",
        },
        coerced=("factor", "order"),
    ),
    ModelSpec(
        name="Quote",
        schema="QuotationResponse",
        doc="One quotation sent to a customer for a project.",
        nouns=("quote", "quotation"),
        expand={"project": "Project"},
        datetimes=("created", "modified", "date", "expiration_date"),
        codes=("tags",),
    ),
    ModelSpec(
        name="Contract",
        schema="ContractResponse",
        doc="One contract signed with a customer for a project.",
        nouns=("contract", "contract"),
        expand={"project": "Project"},
        datetimes=("created", "modified", "date", "expiration_date"),
    ),
    ModelSpec(
        name="Invoice",
        schema="FactuurResponse",
        doc="One invoice issued for a project.",
        nouns=("invoice", "invoice"),
        expand={"project": "Project"},
        datetimes=("created", "modified", "expiration", "date", "payment_date"),
        codes=("tags",),
        nullable=("integration_reference_id",),
    ),
    ModelSpec(
        name="LedgerCode",
        schema="LedgerResponse",
        doc="One ledger account that financial lines book to.",
        nouns=("ledger code", "ledger account"),
    ),
    ModelSpec(
        name="TaxClass",
        schema="TaxClassResponse",
        doc="One tax class applied to financial lines.",
        nouns=("tax class", "tax class"),
    ),
    ModelSpec(
        name="InvoiceLine",
        schema="InvoiceLineResponse",
        doc="One VAT line on a quote, contract, or invoice.",
        nouns=("invoice line", "VAT line"),
        expand={"ledger": "LedgerCode"},
    ),
    ModelSpec(
        name="Payment",
        schema="PaymentResponse",
        doc="One payment recorded against an invoice.",
        nouns=("payment", "payment"),
        expand={"invoice": "Invoice"},
    ),
    ModelSpec(
        name="Subrental",
        schema="SubrentalResponse",
        doc="One subrental order placed with an external supplier.",
        nouns=("subrental", "subrental"),
        expand={
            "status": "Status",
            "asset_location_to": "StockLocation",
            "asset_location_from": "StockLocation",
            "supplier_project": "Project",
        },
        coerced=("number",),
        codes=("tags",),
    ),
    ModelSpec(
        name="SubrentalEquipmentGroup",
        schema="SubrentalEquipmentGroupResponse",
        doc="One equipment group inside a subrental.",
        nouns=("subrental group", "group"),
        expand={"subrental": "Subrental"},
        coerced=("order",),
    ),
    ModelSpec(
        name="SubrentalEquipment",
        schema="SubrentalEquipmentResponse",
        doc="One equipment line inside a subrental.",
        nouns=("subrental equipment", "subrental line"),
        expand={
            "subrental_group": "SubrentalEquipmentGroup",
            "equipment": "Equipment",
            "parent": "SubrentalEquipment",
        },
        coerced=("factor", "order"),
    ),
    ModelSpec(
        name="PurchaseOrder",
        schema="PurchaseOrderResponse",
        doc="One purchase order sent to a supplier.",
        nouns=("purchase order", "purchase order"),
        expand={"delivery_warehouse": "StockLocation"},
        datetimes=("date_of_issue", "approved_at"),
        codes=("tags",),
        nullable=("export_message",),
    ),
    ModelSpec(
        name="PurchaseOrderCost",
        schema="PurchaseOrderCostResponse",
        doc="One underlying cost line of a purchase order.",
        nouns=("purchase order cost", "cost line"),
        expand={"purchase_order": "PurchaseOrder"},
    ),
    ModelSpec(
        name="PurchaseOrderGlobalCost",
        schema="PurchaseOrderGlobalCostResponse",
        doc="One global cost line of a purchase order.",
        nouns=("global cost", "global cost line"),
        expand={"purchase_order": "PurchaseOrder", "taxclass": "TaxClass"},
    ),
    ModelSpec(
        name="Crew",
        schema="CrewResponse",
        doc="One crew member registered in the account.",
        nouns=("crew", "crew member"),
        expand={"folder": "Folder", "default_warehouse": "StockLocation"},
        datetimes=("birthdate", "contract_date"),
        coerced=("contract",),
        codes=("tags",),
    ),
    ModelSpec(
        name="CrewAvailability",
        schema="CrewAvailabilityResponse",
        doc="One availability window registered for one crew member.",
        nouns=("availability", "availability window"),
        expand={"crewmember": "Crew"},
        datetimes=("created", "modified", "recurrence_enddate"),
    ),
    ModelSpec(
        name="CrewRate",
        schema="CrewRatesResponse",
        doc="One cost rate assigned to one crew member.",
        nouns=("crew rate", "crew rate"),
        expand={"medewerker": "Crew"},
    ),
    ModelSpec(
        name="Appointment",
        schema="AppointmentResponse",
        doc="One calendar appointment in the crew planner.",
        nouns=("appointment", "appointment"),
        datetimes=("created", "modified", "recurrence_enddate"),
    ),
    ModelSpec(
        name="AppointmentCrew",
        schema="AppointmentCrewResponse",
        doc="One crew member attached to one appointment.",
        nouns=("appointment crew", "attachment"),
        expand={"appointment": "Appointment", "crew": "Crew"},
    ),
    ModelSpec(
        name="Invitation",
        schema="InvitationsResponse",
        doc="One planning invitation sent to one crew member.",
        nouns=("invitation", "planning invitation"),
        expand={"crewmember": "Crew"},
    ),
    ModelSpec(
        name="LeaveType",
        schema="LeaveTypesResponse",
        doc="One leave type that time registration books to.",
        nouns=("leave type", "leave type"),
        datetimes=("balance_start_date",),
    ),
    ModelSpec(
        name="LeaveRequest",
        schema="LeaveRequestResponse",
        doc="One leave request submitted by one crew member.",
        nouns=("leave request", "leave request"),
        expand={"requested_for": "Crew"},
    ),
    ModelSpec(
        name="LeaveMutation",
        schema="LeaveMutationsResponse",
        doc="One leave balance mutation for one crew member.",
        nouns=("leave mutation", "balance mutation"),
        expand={"crewmember": "Crew", "leavetype": "LeaveType"},
        datetimes=("mutation_date",),
    ),
    ModelSpec(
        name="TimeRegistration",
        schema="TimeRegistrationResponse",
        doc="One worked or leave time registration of one crew member.",
        nouns=("time registration", "registration"),
        expand={"crewmember": "Crew", "leavetype": "LeaveType", "leaverequest": "LeaveRequest"},
    ),
    ModelSpec(
        name="TimeRegistrationActivity",
        schema="TimeRegistrationActivityResponse",
        doc="One activity line inside one time registration.",
        nouns=("activity", "activity line"),
        expand={
            "time_registration": "TimeRegistration",
            "project_function": "ProjectFunction",
            "subproject_function": "ProjectFunction",
        },
    ),
    ModelSpec(
        name="Contact",
        schema="ContactResponse",
        doc="One customer or supplier contact registered in the account.",
        nouns=("contact", "contact"),
        expand={"folder": "Folder", "default_person": "ContactPerson"},
        codes=("tags",),
    ),
    ModelSpec(
        name="ContactPerson",
        schema="ContactPersonResponse",
        doc="One person working at one contact.",
        nouns=("contact person", "contact person"),
        expand={"contact": "Contact"},
        codes=("tags",),
    ),
    ModelSpec(
        name="TaskStatus",
        schema="TaskStatusResponse",
        doc="One status that a task can carry.",
        nouns=("task status", "status"),
        coerced=("order",),
    ),
    ModelSpec(
        name="Task",
        schema="TaskResponse",
        doc="One task tracked against one item in the account.",
        nouns=("task", "task"),
        expand={"status": "TaskStatus"},
        datetimes=("created", "modified"),
        coerced=("order", "public"),
        codes=("tags",),
    ),
    ModelSpec(
        name="Subtask",
        schema="SubtaskResponse",
        doc="One checklist line inside one task.",
        nouns=("subtask", "checklist line"),
        expand={"task": "Task"},
    ),
    ModelSpec(
        name="TaskAssignment",
        schema="TaskAssignmentResponse",
        doc="One crew member assigned to one task.",
        nouns=("task assignment", "assignment"),
        expand={"task": "Task", "crew": "Crew"},
    ),
    ModelSpec(
        name="FileFolder",
        schema="FileFolderResponse",
        doc="One folder that groups the files of one item.",
        nouns=("file folder", "folder"),
        expand={"parent": "FileFolder"},
    ),
    ModelSpec(
        name="File",
        schema="FileResponse",
        doc="One file stored against one item in the account.",
        nouns=("file", "stored file"),
        expand={"folder": "FileFolder"},
        datetimes=("created", "modified", "expiration"),
    ),
    ModelSpec(
        name="Rate",
        schema="CrewRateResponse",
        doc="One rate definition that prices or costs book against.",
        nouns=("rate", "rate definition"),
    ),
    ModelSpec(
        name="RateFactor",
        schema="CrewRateFactorResponse",
        doc="One bracket inside the price or cost table of a rate.",
        nouns=("rate factor", "rate bracket"),
        expand={"rate_id": "Rate"},
    ),
    ModelSpec(
        name="FactorGroup",
        schema="FactorGroupsResponse",
        doc="One group of day factors applied to rental prices.",
        nouns=("factor group", "group"),
    ),
    ModelSpec(
        name="Factor",
        schema="FactorsResponse",
        doc="One day bracket inside a factor group.",
        nouns=("factor", "day bracket"),
        expand={"factor_group": "FactorGroup"},
        coerced=("factor",),
    ),
)
