"""Convert raw Rentman payloads into result models.

A model parser raises ValueError for an object without a usable id.
parse_page, parse_envelope_item, and expanded links drop such objects.

Generated by scripts/generate.py from scripts/resources.py. Do not edit.
"""

from collections.abc import Mapping
from typing import Any

from ._fields import (
    bool_field,
    codes_field,
    coerced_str_field,
    custom_field,
    datetime_field,
    float_field,
    int_field,
    link_field,
    link_or_model_field,
    parse_envelope_item,
    parse_page,
    required_id,
    str_field,
    str_or_none_field,
)
from .models import (
    Accessory,
    ActualContent,
    Alternative,
    Appointment,
    AppointmentCrew,
    Contact,
    ContactPerson,
    Contract,
    Crew,
    CrewAvailability,
    CrewRate,
    Equipment,
    EquipmentAssignedSerial,
    EquipmentSetContent,
    ExtraInputField,
    Factor,
    FactorGroup,
    File,
    FileFolder,
    Folder,
    Invitation,
    Invoice,
    InvoiceLine,
    LeaveMutation,
    LeaveRequest,
    LeaveType,
    LedgerCode,
    Payment,
    Project,
    ProjectCost,
    ProjectCrew,
    ProjectEquipment,
    ProjectEquipmentGroup,
    ProjectFunction,
    ProjectFunctionGroup,
    ProjectRequest,
    ProjectRequestEquipment,
    ProjectStatus,
    ProjectType,
    ProjectVehicle,
    PurchaseOrder,
    PurchaseOrderCost,
    PurchaseOrderGlobalCost,
    Quote,
    Rate,
    RateFactor,
    RentmanLink,
    Repair,
    SerialNumber,
    Status,
    StockLocation,
    StockMovement,
    Subproject,
    Subrental,
    SubrentalEquipment,
    SubrentalEquipmentGroup,
    Subtask,
    Supplier,
    Task,
    TaskAssignment,
    TaskStatus,
    TaxClass,
    TimeRegistration,
    TimeRegistrationActivity,
    Vehicle,
    WarehouseStatus,
)

__all__ = [
    "parse_accessory",
    "parse_actual_content",
    "parse_alternative",
    "parse_appointment",
    "parse_appointment_crew",
    "parse_contact",
    "parse_contact_person",
    "parse_contract",
    "parse_crew",
    "parse_crew_availability",
    "parse_crew_rate",
    "parse_envelope_item",
    "parse_equipment",
    "parse_equipment_assigned_serial",
    "parse_equipment_set_content",
    "parse_extra_input_field",
    "parse_factor",
    "parse_factor_group",
    "parse_file",
    "parse_file_folder",
    "parse_folder",
    "parse_invitation",
    "parse_invoice",
    "parse_invoice_line",
    "parse_leave_mutation",
    "parse_leave_request",
    "parse_leave_type",
    "parse_ledger_code",
    "parse_page",
    "parse_payment",
    "parse_project",
    "parse_project_cost",
    "parse_project_crew",
    "parse_project_equipment",
    "parse_project_equipment_group",
    "parse_project_function",
    "parse_project_function_group",
    "parse_project_request",
    "parse_project_request_equipment",
    "parse_project_status",
    "parse_project_type",
    "parse_project_vehicle",
    "parse_purchase_order",
    "parse_purchase_order_cost",
    "parse_purchase_order_global_cost",
    "parse_quote",
    "parse_rate",
    "parse_rate_factor",
    "parse_repair",
    "parse_serial_number",
    "parse_status",
    "parse_stock_location",
    "parse_stock_movement",
    "parse_subproject",
    "parse_subrental",
    "parse_subrental_equipment",
    "parse_subrental_equipment_group",
    "parse_subtask",
    "parse_supplier",
    "parse_task",
    "parse_task_assignment",
    "parse_task_status",
    "parse_tax_class",
    "parse_time_registration",
    "parse_time_registration_activity",
    "parse_vehicle",
    "parse_warehouse_status",
]


def parse_equipment(data: Mapping[str, Any]) -> Equipment:
    """Build the equipment model from one equipment payload."""
    return Equipment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        folder=link_or_model_field(data, "folder", parse_folder),
        code=str_field(data, "code"),
        factor_group=link_field(data, "factor_group"),
        name=str_field(data, "name"),
        internal_remark=str_field(data, "internal_remark"),
        external_remark=str_field(data, "external_remark"),
        unit=str_field(data, "unit"),
        in_shop=bool_field(data, "in_shop"),
        surface_article=bool_field(data, "surface_article"),
        shop_description_short=str_field(data, "shop_description_short"),
        shop_description_long=str_field(data, "shop_description_long"),
        shop_seo_title=str_field(data, "shop_seo_title"),
        shop_seo_keyword=str_field(data, "shop_seo_keyword"),
        shop_seo_description=str_field(data, "shop_seo_description"),
        shop_featured=bool_field(data, "shop_featured"),
        price=float_field(data, "price"),
        subrental_costs=float_field(data, "subrental_costs"),
        critical_stock_level=int_field(data, "critical_stock_level"),
        type=str_field(data, "type"),
        rental_sales=str_field(data, "rental_sales"),
        temporary=bool_field(data, "temporary"),
        in_planner=bool_field(data, "in_planner"),
        in_archive=bool_field(data, "in_archive"),
        stock_management=str_field(data, "stock_management"),
        taxclass=link_field(data, "taxclass"),
        list_price=float_field(data, "list_price"),
        volume=float_field(data, "volume"),
        packed_per=int_field(data, "packed_per"),
        height=float_field(data, "height"),
        width=float_field(data, "width"),
        length=float_field(data, "length"),
        weight=float_field(data, "weight"),
        empty_weight=float_field(data, "empty_weight"),
        power=float_field(data, "power"),
        current=float_field(data, "current"),
        country_of_origin=str_field(data, "country_of_origin"),
        image=link_field(data, "image"),
        ledger=link_field(data, "ledger"),
        ledger_debit=link_field(data, "ledger_debit"),
        defaultgroup=str_field(data, "defaultgroup"),
        is_combination=bool_field(data, "is_combination"),
        is_physical=str_field(data, "is_physical"),
        can_edit_content_during_planning=bool_field(data, "can_edit_content_during_planning"),
        strict_container_content=str_field(data, "strict_container_content"),
        qrcodes=codes_field(data, "qrcodes"),
        qrcodes_of_serial_numbers=codes_field(data, "qrcodes_of_serial_numbers"),
        tags=codes_field(data, "tags"),
        current_quantity_excl_cases=int_field(data, "current_quantity_excl_cases"),
        current_quantity=int_field(data, "current_quantity"),
        quantity_in_cases=int_field(data, "quantity_in_cases"),
        location_in_warehouse=str_field(data, "location_in_warehouse"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_serial_number(data: Mapping[str, Any]) -> SerialNumber:
    """Build the serial number model from one serial number payload."""
    return SerialNumber(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        serial=str_field(data, "serial"),
        purchasedate=datetime_field(data, "purchasedate"),
        depreciation_monthly=float_field(data, "depreciation_monthly"),
        book_value=float_field(data, "book_value"),
        residual_value=float_field(data, "residual_value"),
        purchase_costs=float_field(data, "purchase_costs"),
        active=bool_field(data, "active"),
        remark=str_field(data, "remark"),
        ref=str_field(data, "ref"),
        asset_location=link_or_model_field(data, "asset_location", parse_stock_location),
        image=link_field(data, "image"),
        current_book_value=float_field(data, "current_book_value"),
        next_inspection=datetime_field(data, "next_inspection"),
        qrcodes=codes_field(data, "qrcodes"),
        tags=codes_field(data, "tags"),
        last_subproject=link_or_model_field(data, "last_subproject", parse_subproject),
        sealed=bool_field(data, "sealed"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_equipment_assigned_serial(data: Mapping[str, Any]) -> EquipmentAssignedSerial:
    """Build the assigned serial model from one assignment payload."""
    return EquipmentAssignedSerial(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        combination=link_or_model_field(data, "combination", parse_serial_number)
        or RentmanLink(str_field(data, "combination")),
        serialnumber=link_or_model_field(data, "serialnumber", parse_serial_number)
        or RentmanLink(str_field(data, "serialnumber")),
        raw=dict(data),
    )


def parse_actual_content(data: Mapping[str, Any]) -> ActualContent:
    """Build the actual content model from one content payload."""
    return ActualContent(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        equipment=link_or_model_field(data, "equipment", parse_equipment),
        serial=link_or_model_field(data, "serial", parse_serial_number),
        quantity=coerced_str_field(data, "quantity"),
        combination_serial=link_or_model_field(data, "combination_serial", parse_serial_number),
        raw=dict(data),
    )


def parse_equipment_set_content(data: Mapping[str, Any]) -> EquipmentSetContent:
    """Build the set content model from one set content payload."""
    return EquipmentSetContent(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        quantity=coerced_str_field(data, "quantity"),
        parent_equipment=link_or_model_field(data, "parent_equipment", parse_equipment)
        or RentmanLink(str_field(data, "parent_equipment")),
        order=coerced_str_field(data, "order"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        is_fixed=str_field(data, "is_fixed"),
        is_physically_connected=str_field(data, "is_physically_connected"),
        raw=dict(data),
    )


def parse_folder(data: Mapping[str, Any]) -> Folder:
    """Build the folder model from one folder payload."""
    return Folder(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        parent=link_or_model_field(data, "parent", parse_folder),
        name=str_field(data, "name"),
        order=coerced_str_field(data, "order"),
        itemtype=str_field(data, "itemtype"),
        path=str_field(data, "path"),
        raw=dict(data),
    )


def parse_stock_location(data: Mapping[str, Any]) -> StockLocation:
    """Build the stock location model from one stock location payload."""
    return StockLocation(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        city=str_field(data, "city"),
        street=str_field(data, "street"),
        house_number=str_field(data, "house_number"),
        postal_code=str_field(data, "postal_code"),
        state_province=str_field(data, "state_province"),
        country=str_field(data, "country"),
        active=bool_field(data, "active"),
        type=str_field(data, "type"),
        color=str_field(data, "color"),
        in_archive=bool_field(data, "in_archive"),
        raw=dict(data),
    )


def parse_warehouse_status(data: Mapping[str, Any]) -> WarehouseStatus:
    """Build the warehouse status model from one warehouse status payload."""
    return WarehouseStatus(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        raw=dict(data),
    )


def parse_status(data: Mapping[str, Any]) -> Status:
    """Build the status model from one status payload."""
    return Status(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        raw=dict(data),
    )


def parse_stock_movement(data: Mapping[str, Any]) -> StockMovement:
    """Build the stock movement model from one stock movement payload."""
    return StockMovement(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        amount=int_field(data, "amount"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        projectequipment=link_or_model_field(data, "projectequipment", parse_project_equipment),
        description=str_field(data, "description"),
        details=str_field(data, "details"),
        date=datetime_field(data, "date"),
        type=str_field(data, "type"),
        stock_location=link_or_model_field(data, "stock_location", parse_stock_location)
        or RentmanLink(str_field(data, "stock_location")),
        api_client=str_field(data, "api_client"),
        raw=dict(data),
    )


def parse_repair(data: Mapping[str, Any]) -> Repair:
    """Build the repair model from one repair payload."""
    return Repair(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        internal_name=str_field(data, "internal_name"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        serialnumber=link_or_model_field(data, "serialnumber", parse_serial_number),
        reporter=link_field(data, "reporter"),
        assignee=link_field(data, "assignee"),
        external_repairer=link_field(data, "external_repairer"),
        number=str_field(data, "number"),
        repairperiod_start=datetime_field(data, "repairperiod_start"),
        repairperiod_end=datetime_field(data, "repairperiod_end"),
        amount=int_field(data, "amount"),
        remark=str_field(data, "remark"),
        repair_costs=float_field(data, "repair_costs"),
        is_usable=str_field(data, "is_usable"),
        costs_charged_to_customer=link_field(data, "costs_charged_to_customer"),
        subproject=link_or_model_field(data, "subproject", parse_subproject),
        stock_location=link_or_model_field(data, "stock_location", parse_stock_location),
        repair_status=str_field(data, "repair_status"),
        unrepairable_of=link_or_model_field(data, "unrepairable_of", parse_repair),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project(data: Mapping[str, Any]) -> Project:
    """Build the project model from one project payload."""
    return Project(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        location=link_field(data, "location"),
        refundabledeposit=float_field(data, "refundabledeposit"),
        deposit_status=str_field(data, "deposit_status"),
        customer=link_field(data, "customer"),
        loc_contact=link_field(data, "loc_contact"),
        cust_contact=link_field(data, "cust_contact"),
        project_type=link_field(data, "project_type"),
        name=str_field(data, "name"),
        reference=str_field(data, "reference"),
        number=str_field(data, "number"),
        account_manager=link_field(data, "account_manager"),
        color=str_field(data, "color"),
        conditions=str_field(data, "conditions"),
        project_total_price=float_field(data, "project_total_price"),
        project_total_price_cancelled=float_field(data, "project_total_price_cancelled"),
        project_rental_price=float_field(data, "project_rental_price"),
        project_sale_price=float_field(data, "project_sale_price"),
        project_crew_price=float_field(data, "project_crew_price"),
        project_transport_price=float_field(data, "project_transport_price"),
        project_other_price=float_field(data, "project_other_price"),
        project_insurance_price=float_field(data, "project_insurance_price"),
        project_services_price=float_field(data, "project_services_price"),
        estimated_cost=float_field(data, "estimated_cost"),
        planned_cost=float_field(data, "planned_cost"),
        actual_cost=float_field(data, "actual_cost"),
        already_invoiced=float_field(data, "already_invoiced"),
        tags=codes_field(data, "tags"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        weight=float_field(data, "weight"),
        power=float_field(data, "power"),
        current=float_field(data, "current"),
        equipment_period_from=datetime_field(data, "equipment_period_from"),
        equipment_period_to=datetime_field(data, "equipment_period_to"),
        purchasecosts=float_field(data, "purchasecosts"),
        volume=float_field(data, "volume"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_subproject(data: Mapping[str, Any]) -> Subproject:
    """Build the subproject model from one subproject payload."""
    return Subproject(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        order=coerced_str_field(data, "order"),
        name=str_field(data, "name"),
        status=link_or_model_field(data, "status", parse_status)
        or RentmanLink(str_field(data, "status")),
        is_template=bool_field(data, "is_template"),
        location=link_field(data, "location"),
        loc_contact=link_field(data, "loc_contact"),
        insurance_rate=float_field(data, "insurance_rate"),
        discount_rental=float_field(data, "discount_rental"),
        discount_sale=float_field(data, "discount_sale"),
        discount_crew=float_field(data, "discount_crew"),
        discount_transport=float_field(data, "discount_transport"),
        discount_additional_costs=float_field(data, "discount_additional_costs"),
        discount_services=float_field(data, "discount_services"),
        discount_subproject=float_field(data, "discount_subproject"),
        discount_fixed=bool_field(data, "discount_fixed"),
        discount_fixed_amount=float_field(data, "discount_fixed_amount"),
        fixed_price=bool_field(data, "fixed_price"),
        in_planning=bool_field(data, "in_planning"),
        in_financial=bool_field(data, "in_financial"),
        asset_location_from=link_or_model_field(data, "asset_location_from", parse_stock_location),
        project_total_price=float_field(data, "project_total_price"),
        project_total_price_cancelled=float_field(data, "project_total_price_cancelled"),
        project_rental_price=float_field(data, "project_rental_price"),
        project_sale_price=float_field(data, "project_sale_price"),
        project_crew_price=float_field(data, "project_crew_price"),
        project_transport_price=float_field(data, "project_transport_price"),
        project_other_price=float_field(data, "project_other_price"),
        project_insurance_price=float_field(data, "project_insurance_price"),
        project_services_price=float_field(data, "project_services_price"),
        estimated_cost=float_field(data, "estimated_cost"),
        planned_cost=float_field(data, "planned_cost"),
        actual_cost=float_field(data, "actual_cost"),
        already_invoiced=float_field(data, "already_invoiced"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        weight=float_field(data, "weight"),
        power=float_field(data, "power"),
        current=float_field(data, "current"),
        purchasecosts=float_field(data, "purchasecosts"),
        volume=float_field(data, "volume"),
        equipment_period_from=datetime_field(data, "equipment_period_from"),
        equipment_period_to=datetime_field(data, "equipment_period_to"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project_equipment(data: Mapping[str, Any]) -> ProjectEquipment:
    """Build the project equipment model from one planned equipment payload."""
    return ProjectEquipment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        equipment=link_or_model_field(data, "equipment", parse_equipment),
        parent=link_or_model_field(data, "parent", parse_project_equipment),
        ledger=link_field(data, "ledger"),
        ledger_debit=link_field(data, "ledger_debit"),
        quantity=coerced_str_field(data, "quantity"),
        quantity_total=int_field(data, "quantity_total"),
        equipment_group=link_field(data, "equipment_group"),
        discount=float_field(data, "discount"),
        is_option=bool_field(data, "is_option"),
        factor=coerced_str_field(data, "factor"),
        order=coerced_str_field(data, "order"),
        unit_price=float_field(data, "unit_price"),
        name=str_field(data, "name"),
        external_remark=str_field(data, "external_remark"),
        internal_remark=str_field(data, "internal_remark"),
        delay_notified=bool_field(data, "delay_notified"),
        duration=float_field(data, "duration"),
        is_delayed=bool_field(data, "is_delayed"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        has_missings=bool_field(data, "has_missings"),
        warehouse_reservations=int_field(data, "warehouse_reservations"),
        subrent_reservations=int_field(data, "subrent_reservations"),
        serial_number_ids=str_field(data, "serial_number_ids"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_accessory(data: Mapping[str, Any]) -> Accessory:
    """Build the accessory model from one accessory payload."""
    return Accessory(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        parent_equipment=link_or_model_field(data, "parent_equipment", parse_equipment)
        or RentmanLink(str_field(data, "parent_equipment")),
        equipment=link_or_model_field(data, "equipment", parse_equipment),
        quantity=int_field(data, "quantity"),
        automatic=bool_field(data, "automatic"),
        skip=bool_field(data, "skip"),
        is_free=bool_field(data, "is_free"),
        order=coerced_str_field(data, "order"),
        add_as_new_line=bool_field(data, "add_as_new_line"),
        raw=dict(data),
    )


def parse_alternative(data: Mapping[str, Any]) -> Alternative:
    """Build the alternative model from one alternative payload."""
    return Alternative(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        alternative=link_or_model_field(data, "alternative", parse_equipment)
        or RentmanLink(str_field(data, "alternative")),
        raw=dict(data),
    )


def parse_supplier(data: Mapping[str, Any]) -> Supplier:
    """Build the supplier model from one supplier payload."""
    return Supplier(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        equipment=link_or_model_field(data, "equipment", parse_equipment)
        or RentmanLink(str_field(data, "equipment")),
        contact=link_field(data, "contact"),
        contactperson=link_field(data, "contactperson"),
        price=float_field(data, "price"),
        details=str_field(data, "details"),
        raw=dict(data),
    )


def parse_vehicle(data: Mapping[str, Any]) -> Vehicle:
    """Build the vehicle model from one vehicle payload."""
    return Vehicle(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        folder=link_or_model_field(data, "folder", parse_folder),
        name=str_field(data, "name"),
        cost_rate=link_field(data, "cost_rate"),
        in_planner=bool_field(data, "in_planner"),
        height=float_field(data, "height"),
        length=float_field(data, "length"),
        width=float_field(data, "width"),
        seats=int_field(data, "seats"),
        inspection_date=datetime_field(data, "inspection_date"),
        licenseplate=str_field(data, "licenseplate"),
        remark=str_field(data, "remark"),
        payload_capacity=float_field(data, "payload_capacity"),
        surface_area=str_field(data, "surface_area"),
        multiple=str_field(data, "multiple"),
        image=link_field(data, "image"),
        asset_location=link_or_model_field(data, "asset_location", parse_stock_location),
        tags=codes_field(data, "tags"),
        distance_cost=float_field(data, "distance_cost"),
        fixed_cost=float_field(data, "fixed_cost"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_extra_input_field(data: Mapping[str, Any]) -> ExtraInputField:
    """Build the extra input field model from one field definition payload."""
    return ExtraInputField(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        itemtype=str_field(data, "itemtype"),
        linkedItemType=str_field(data, "linkedItemType"),
        parent=link_or_model_field(data, "parent", parse_extra_input_field),
        type=str_field(data, "type"),
        order=coerced_str_field(data, "order"),
        hidden=bool_field(data, "hidden"),
        classified=bool_field(data, "classified"),
        search_include=bool_field(data, "search_include"),
        search_minlength=int_field(data, "search_minlength"),
        is_customfield_mandatory=bool_field(data, "is_customfield_mandatory"),
        raw=dict(data),
    )


def parse_project_status(data: Mapping[str, Any]) -> ProjectStatus:
    """Build the project status model from one status payload."""
    return ProjectStatus(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        raw=dict(data),
    )


def parse_project_type(data: Mapping[str, Any]) -> ProjectType:
    """Build the project type model from one type payload."""
    return ProjectType(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        color=str_field(data, "color"),
        type=str_field(data, "type"),
        raw=dict(data),
    )


def parse_project_function_group(data: Mapping[str, Any]) -> ProjectFunctionGroup:
    """Build the function group model from one group payload."""
    return ProjectFunctionGroup(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        subproject=link_or_model_field(data, "subproject", parse_subproject)
        or RentmanLink(str_field(data, "subproject")),
        duration=float_field(data, "duration"),
        planperiod_start_schedule_is_start=str_field(data, "planperiod_start_schedule_is_start"),
        usageperiod_start_schedule_is_start=str_field(data, "usageperiod_start_schedule_is_start"),
        planperiod_end_schedule_is_start=str_field(data, "planperiod_end_schedule_is_start"),
        usageperiod_end_schedule_is_start=str_field(data, "usageperiod_end_schedule_is_start"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        remark=str_field(data, "remark"),
        raw=dict(data),
    )


def parse_project_function(data: Mapping[str, Any]) -> ProjectFunction:
    """Build the function model from one planned function payload."""
    return ProjectFunction(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        cost_rate=link_field(data, "cost_rate"),
        cost_accommodation=float_field(data, "cost_accommodation"),
        cost_catering=float_field(data, "cost_catering"),
        cost_travel=float_field(data, "cost_travel"),
        cost_other=float_field(data, "cost_other"),
        price_rate=link_field(data, "price_rate"),
        price_accommodation=float_field(data, "price_accommodation"),
        price_catering=float_field(data, "price_catering"),
        price_travel=float_field(data, "price_travel"),
        price_other=float_field(data, "price_other"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        subproject=link_or_model_field(data, "subproject", parse_subproject)
        or RentmanLink(str_field(data, "subproject")),
        is_template=bool_field(data, "is_template"),
        group=link_or_model_field(data, "group", parse_project_function_group),
        name_external=str_field(data, "name_external"),
        name=str_field(data, "name"),
        travel_time_before=float_field(data, "travel_time_before"),
        travel_time_after=float_field(data, "travel_time_after"),
        use_travel_time_from_location=bool_field(data, "use_travel_time_from_location"),
        use_distance_from_location=bool_field(data, "use_distance_from_location"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        planperiod_start_schedule_is_start=str_field(data, "planperiod_start_schedule_is_start"),
        usageperiod_start_schedule_is_start=str_field(data, "usageperiod_start_schedule_is_start"),
        planperiod_end_schedule_is_start=str_field(data, "planperiod_end_schedule_is_start"),
        usageperiod_end_schedule_is_start=str_field(data, "usageperiod_end_schedule_is_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        type=str_field(data, "type"),
        duration=float_field(data, "duration"),
        amount=int_field(data, "amount"),
        break_=float_field(data, "break"),
        distance=float_field(data, "distance"),
        twoway=bool_field(data, "twoway"),
        taxclass=link_field(data, "taxclass"),
        ledger=link_field(data, "ledger"),
        ledger_debit=link_field(data, "ledger_debit"),
        order=coerced_str_field(data, "order"),
        remark_client=str_field(data, "remark_client"),
        remark_planner=str_field(data, "remark_planner"),
        remark_crew=str_field(data, "remark_crew"),
        in_financial=bool_field(data, "in_financial"),
        in_planning=bool_field(data, "in_planning"),
        is_plannable=bool_field(data, "is_plannable"),
        recurrence_group=int_field(data, "recurrence_group"),
        recurrence_enddate=datetime_field(data, "recurrence_enddate"),
        recurrence_interval_unit=str_field(data, "recurrence_interval_unit"),
        recurrence_interval=int_field(data, "recurrence_interval"),
        recurrence_weekdays=str_or_none_field(data, "recurrence_weekdays"),
        price_fixed=float_field(data, "price_fixed"),
        price_variable=float_field(data, "price_variable"),
        costs_fixed=float_field(data, "costs_fixed"),
        costs_variable=float_field(data, "costs_variable"),
        price_total=float_field(data, "price_total"),
        costs_total=float_field(data, "costs_total"),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project_crew(data: Mapping[str, Any]) -> ProjectCrew:
    """Build the project crew model from one crew planning payload."""
    return ProjectCrew(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        cost_rate=link_field(data, "cost_rate"),
        cost_accommodation=float_field(data, "cost_accommodation"),
        cost_catering=float_field(data, "cost_catering"),
        cost_travel=float_field(data, "cost_travel"),
        cost_other=float_field(data, "cost_other"),
        function=link_or_model_field(data, "function", parse_project_function)
        or RentmanLink(str_field(data, "function")),
        crewmember=link_field(data, "crewmember") or RentmanLink(str_field(data, "crewmember")),
        visible=bool_field(data, "visible"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        transport=str_field(data, "transport"),
        remark=str_field(data, "remark"),
        remark_planner=str_field(data, "remark_planner"),
        invoice_reference=str_field(data, "invoice_reference"),
        project_leader=bool_field(data, "project_leader"),
        is_visible_on_dashboard=bool_field(data, "is_visible_on_dashboard"),
        costs=float_field(data, "costs"),
        cost_actual=float_field(data, "cost_actual"),
        hours_registered=float_field(data, "hours_registered"),
        hours_planned=float_field(data, "hours_planned"),
        cost_planned=float_field(data, "cost_planned"),
        diff_cost=float_field(data, "diff_cost"),
        diff_hours=float_field(data, "diff_hours"),
        activity_status=str_field(data, "activity_status"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project_vehicle(data: Mapping[str, Any]) -> ProjectVehicle:
    """Build the project vehicle model from one transport planning payload."""
    return ProjectVehicle(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        cost_rate=link_field(data, "cost_rate"),
        function=link_or_model_field(data, "function", parse_project_function)
        or RentmanLink(str_field(data, "function")),
        transport=str_field(data, "transport"),
        vehicle=link_or_model_field(data, "vehicle", parse_vehicle)
        or RentmanLink(str_field(data, "vehicle")),
        planningperiod_start=datetime_field(data, "planningperiod_start"),
        planningperiod_end=datetime_field(data, "planningperiod_end"),
        remark=str_field(data, "remark"),
        remark_planner=str_field(data, "remark_planner"),
        costs=float_field(data, "costs"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project_equipment_group(data: Mapping[str, Any]) -> ProjectEquipmentGroup:
    """Build the equipment group model from one group payload."""
    return ProjectEquipmentGroup(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        subproject=link_or_model_field(data, "subproject", parse_subproject)
        or RentmanLink(str_field(data, "subproject")),
        additional_scanned=bool_field(data, "additional_scanned"),
        name=str_field(data, "name"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        duration=float_field(data, "duration"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        is_delayed=bool_field(data, "is_delayed"),
        order=coerced_str_field(data, "order"),
        in_price_calculation=bool_field(data, "in_price_calculation"),
        remark=str_field(data, "remark"),
        weight=float_field(data, "weight"),
        power=float_field(data, "power"),
        current=float_field(data, "current"),
        volume=float_field(data, "volume"),
        total_new_price=float_field(data, "total_new_price"),
        raw=dict(data),
    )


def parse_project_cost(data: Mapping[str, Any]) -> ProjectCost:
    """Build the project cost model from one cost line payload."""
    return ProjectCost(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        remark=str_field(data, "remark"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        quantity=int_field(data, "quantity"),
        discount=float_field(data, "discount"),
        order=coerced_str_field(data, "order"),
        subproject=link_or_model_field(data, "subproject", parse_subproject)
        or RentmanLink(str_field(data, "subproject")),
        is_template=bool_field(data, "is_template"),
        taxclass=link_field(data, "taxclass"),
        ledger=link_field(data, "ledger"),
        ledger_debit=link_field(data, "ledger_debit"),
        sale_price=float_field(data, "sale_price"),
        purchase_price=float_field(data, "purchase_price"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_project_request(data: Mapping[str, Any]) -> ProjectRequest:
    """Build the project request model from one request payload."""
    return ProjectRequest(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        linked_contact=link_field(data, "linked_contact"),
        contact_mailing_number=str_field(data, "contact_mailing_number"),
        contact_mailing_country=str_field(data, "contact_mailing_country"),
        contact_name=str_field(data, "contact_name"),
        contact_mailing_postalcode=str_field(data, "contact_mailing_postalcode"),
        contact_phone=str_field(data, "contact_phone"),
        contact_mailing_city=str_field(data, "contact_mailing_city"),
        contact_mailing_street=str_field(data, "contact_mailing_street"),
        linked_contact_person=link_field(data, "linked_contact_person"),
        contact_person_lastname=str_field(data, "contact_person_lastname"),
        contact_person_email=str_field(data, "contact_person_email"),
        contact_person_middle_name=str_field(data, "contact_person_middle_name"),
        contact_person_first_name=str_field(data, "contact_person_first_name"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        is_paid=bool_field(data, "is_paid"),
        language=str_field(data, "language"),
        in_=datetime_field(data, "in"),
        out_=datetime_field(data, "out"),
        linked_location=link_field(data, "linked_location"),
        location_mailing_number=str_field(data, "location_mailing_number"),
        location_mailing_country=str_field(data, "location_mailing_country"),
        location_name=str_field(data, "location_name"),
        location_mailing_postalcode=str_field(data, "location_mailing_postalcode"),
        location_mailing_city=str_field(data, "location_mailing_city"),
        location_mailing_street=str_field(data, "location_mailing_street"),
        location_phone=str_field(data, "location_phone"),
        name=str_field(data, "name"),
        external_reference=int_field(data, "external_reference"),
        remark=str_field(data, "remark"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        price=float_field(data, "price"),
        linked_project=link_or_model_field(data, "linked_project", parse_project),
        source=str_field(data, "source"),
        status=str_field(data, "status"),
        raw=dict(data),
    )


def parse_project_request_equipment(data: Mapping[str, Any]) -> ProjectRequestEquipment:
    """Build the request equipment model from one requested line payload."""
    return ProjectRequestEquipment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        quantity=int_field(data, "quantity"),
        quantity_total=int_field(data, "quantity_total"),
        is_comment=bool_field(data, "is_comment"),
        is_kit=bool_field(data, "is_kit"),
        discount=float_field(data, "discount"),
        linked_equipment=link_or_model_field(data, "linked_equipment", parse_equipment),
        name=str_field(data, "name"),
        external_remark=str_field(data, "external_remark"),
        parent=link_or_model_field(data, "parent", parse_project_request_equipment),
        unit_price=float_field(data, "unit_price"),
        project_request=link_or_model_field(data, "project_request", parse_project_request)
        or RentmanLink(str_field(data, "project_request")),
        factor=coerced_str_field(data, "factor"),
        order=coerced_str_field(data, "order"),
        raw=dict(data),
    )


def parse_quote(data: Mapping[str, Any]) -> Quote:
    """Build the quote model from one quotation payload."""
    return Quote(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        number=str_field(data, "number"),
        customer=link_field(data, "customer"),
        contact=link_field(data, "contact"),
        date=datetime_field(data, "date"),
        expiration_date=datetime_field(data, "expiration_date"),
        version=int_field(data, "version"),
        subject=str_field(data, "subject"),
        show_tax=bool_field(data, "show_tax"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        filename=str_field(data, "filename"),
        project_total_price=float_field(data, "project_total_price"),
        project_total_price_cancelled=float_field(data, "project_total_price_cancelled"),
        project_rental_price=float_field(data, "project_rental_price"),
        project_sale_price=float_field(data, "project_sale_price"),
        project_crew_price=float_field(data, "project_crew_price"),
        project_transport_price=float_field(data, "project_transport_price"),
        project_other_price=float_field(data, "project_other_price"),
        project_insurance_price=float_field(data, "project_insurance_price"),
        project_services_price=float_field(data, "project_services_price"),
        price=float_field(data, "price"),
        price_invat=float_field(data, "price_invat"),
        vat_amount=float_field(data, "vat_amount"),
        tags=codes_field(data, "tags"),
        raw=dict(data),
    )


def parse_contract(data: Mapping[str, Any]) -> Contract:
    """Build the contract model from one contract payload."""
    return Contract(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        number=str_field(data, "number"),
        customer=link_field(data, "customer"),
        contact=link_field(data, "contact"),
        date=datetime_field(data, "date"),
        expiration_date=datetime_field(data, "expiration_date"),
        version=int_field(data, "version"),
        subject=str_field(data, "subject"),
        show_tax=bool_field(data, "show_tax"),
        project=link_or_model_field(data, "project", parse_project)
        or RentmanLink(str_field(data, "project")),
        filename=str_field(data, "filename"),
        project_total_price=float_field(data, "project_total_price"),
        project_total_price_cancelled=float_field(data, "project_total_price_cancelled"),
        project_rental_price=float_field(data, "project_rental_price"),
        project_sale_price=float_field(data, "project_sale_price"),
        project_crew_price=float_field(data, "project_crew_price"),
        project_transport_price=float_field(data, "project_transport_price"),
        project_other_price=float_field(data, "project_other_price"),
        project_insurance_price=float_field(data, "project_insurance_price"),
        project_services_price=float_field(data, "project_services_price"),
        price=float_field(data, "price"),
        price_invat=float_field(data, "price_invat"),
        vat_amount=float_field(data, "vat_amount"),
        raw=dict(data),
    )


def parse_invoice(data: Mapping[str, Any]) -> Invoice:
    """Build the invoice model from one invoice payload."""
    return Invoice(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        customer=link_field(data, "customer"),
        account_manager=link_field(data, "account_manager"),
        contact=link_field(data, "contact"),
        expiration=datetime_field(data, "expiration"),
        date=datetime_field(data, "date"),
        number=str_field(data, "number"),
        procent=float_field(data, "procent"),
        from_project=bool_field(data, "from_project"),
        subject=str_field(data, "subject"),
        finalized=bool_field(data, "finalized"),
        integration_reference_id=str_or_none_field(data, "integration_reference_id"),
        project=link_or_model_field(data, "project", parse_project),
        filename=str_field(data, "filename"),
        project_total_price=float_field(data, "project_total_price"),
        project_total_price_cancelled=float_field(data, "project_total_price_cancelled"),
        project_rental_price=float_field(data, "project_rental_price"),
        project_sale_price=float_field(data, "project_sale_price"),
        project_crew_price=float_field(data, "project_crew_price"),
        project_transport_price=float_field(data, "project_transport_price"),
        project_other_price=float_field(data, "project_other_price"),
        project_insurance_price=float_field(data, "project_insurance_price"),
        project_services_price=float_field(data, "project_services_price"),
        sum_factuurregels=float_field(data, "sum_factuurregels"),
        price=float_field(data, "price"),
        price_invat=float_field(data, "price_invat"),
        vat_amount=float_field(data, "vat_amount"),
        invoicetype=str_field(data, "invoicetype"),
        outstanding_balance=float_field(data, "outstanding_balance"),
        total_paid=float_field(data, "total_paid"),
        is_paid=bool_field(data, "is_paid"),
        date_sent=datetime_field(data, "date_sent"),
        payment_reminder_sent=int_field(data, "payment_reminder_sent"),
        final_payment_reminder_sent=datetime_field(data, "final_payment_reminder_sent"),
        payment_date=datetime_field(data, "payment_date"),
        days_after_expiry=int_field(data, "days_after_expiry"),
        tags=codes_field(data, "tags"),
        raw=dict(data),
    )


def parse_ledger_code(data: Mapping[str, Any]) -> LedgerCode:
    """Build the ledger code model from one ledger account payload."""
    return LedgerCode(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        code=str_field(data, "code"),
        is_credit=bool_field(data, "is_credit"),
        is_debit=bool_field(data, "is_debit"),
        raw=dict(data),
    )


def parse_tax_class(data: Mapping[str, Any]) -> TaxClass:
    """Build the tax class model from one tax class payload."""
    return TaxClass(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        code=str_field(data, "code"),
        type=str_field(data, "type"),
        raw=dict(data),
    )


def parse_invoice_line(data: Mapping[str, Any]) -> InvoiceLine:
    """Build the invoice line model from one VAT line payload."""
    return InvoiceLine(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        item=int_field(data, "item"),
        base=float_field(data, "base"),
        ledger=link_or_model_field(data, "ledger", parse_ledger_code)
        or RentmanLink(str_field(data, "ledger")),
        vatrate=float_field(data, "vatrate"),
        vatamount=float_field(data, "vatamount"),
        priceincl=float_field(data, "priceincl"),
        ledgercode=str_field(data, "ledgercode"),
        parent_api_path=str_field(data, "parent_api_path"),
        raw=dict(data),
    )


def parse_payment(data: Mapping[str, Any]) -> Payment:
    """Build the payment model from one payment payload."""
    return Payment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        invoice=link_or_model_field(data, "invoice", parse_invoice)
        or RentmanLink(str_field(data, "invoice")),
        moment=datetime_field(data, "moment"),
        amount=float_field(data, "amount"),
        description=str_field(data, "description"),
        payment_import_source=str_field(data, "payment_import_source"),
        raw=dict(data),
    )


def parse_subrental(data: Mapping[str, Any]) -> Subrental:
    """Build the subrental model from one subrental payload."""
    return Subrental(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        accountmanager=link_field(data, "accountmanager"),
        reference=str_field(data, "reference"),
        supplier=link_field(data, "supplier"),
        number=coerced_str_field(data, "number"),
        contactperson=link_field(data, "contactperson"),
        location=link_field(data, "location"),
        location_contact=link_field(data, "location_contact"),
        usageperiod_start=datetime_field(data, "usageperiod_start"),
        usageperiod_end=datetime_field(data, "usageperiod_end"),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        delivery_in=datetime_field(data, "delivery_in"),
        delivery_out=datetime_field(data, "delivery_out"),
        equipment_cost=float_field(data, "equipment_cost"),
        price=float_field(data, "price"),
        extra_cost=float_field(data, "extra_cost"),
        auto_update_costs=bool_field(data, "auto_update_costs"),
        remark=str_field(data, "remark"),
        type=str_field(data, "type"),
        status=link_or_model_field(data, "status", parse_status)
        or RentmanLink(str_field(data, "status")),
        sent=datetime_field(data, "sent"),
        asset_location_to=link_or_model_field(data, "asset_location_to", parse_stock_location),
        asset_location_from=link_or_model_field(data, "asset_location_from", parse_stock_location),
        is_internal=bool_field(data, "is_internal"),
        supplier_project=link_or_model_field(data, "supplier_project", parse_project),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_subrental_equipment_group(data: Mapping[str, Any]) -> SubrentalEquipmentGroup:
    """Build the subrental group model from one group payload."""
    return SubrentalEquipmentGroup(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        subrental=link_or_model_field(data, "subrental", parse_subrental)
        or RentmanLink(str_field(data, "subrental")),
        name=str_field(data, "name"),
        order=coerced_str_field(data, "order"),
        supplier_category=link_field(data, "supplier_category"),
        raw=dict(data),
    )


def parse_subrental_equipment(data: Mapping[str, Any]) -> SubrentalEquipment:
    """Build the subrental equipment model from one subrental line payload."""
    return SubrentalEquipment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        subrental_group=link_or_model_field(
            data, "subrental_group", parse_subrental_equipment_group
        )
        or RentmanLink(str_field(data, "subrental_group")),
        equipment=link_or_model_field(data, "equipment", parse_equipment),
        parent=link_or_model_field(data, "parent", parse_subrental_equipment),
        planperiod_start=datetime_field(data, "planperiod_start"),
        planperiod_end=datetime_field(data, "planperiod_end"),
        name=str_field(data, "name"),
        quantity=int_field(data, "quantity"),
        quantity_total=int_field(data, "quantity_total"),
        unit_price=float_field(data, "unit_price"),
        discount=float_field(data, "discount"),
        factor=coerced_str_field(data, "factor"),
        order=coerced_str_field(data, "order"),
        remark=str_field(data, "remark"),
        lineprice=float_field(data, "lineprice"),
        supplier_planningmateriaal=link_field(data, "supplier_planningmateriaal"),
        raw=dict(data),
    )


def parse_purchase_order(data: Mapping[str, Any]) -> PurchaseOrder:
    """Build the purchase order model from one purchase order payload."""
    return PurchaseOrder(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        filename=str_field(data, "filename"),
        subject=str_field(data, "subject"),
        owner=link_field(data, "owner") or RentmanLink(str_field(data, "owner")),
        date_of_issue=datetime_field(data, "date_of_issue"),
        delivery_date=datetime_field(data, "delivery_date"),
        description=str_field(data, "description"),
        number=str_field(data, "number"),
        approval_status=str_field(data, "approval_status"),
        previous_status=str_field(data, "previous_status"),
        approved_amount=float_field(data, "approved_amount"),
        supplier=link_field(data, "supplier"),
        contact_person=link_field(data, "contact_person"),
        delivery_type=str_field(data, "delivery_type"),
        delivery_location=link_field(data, "delivery_location"),
        delivery_location_person=link_field(data, "delivery_location_person"),
        delivery_warehouse=link_or_model_field(data, "delivery_warehouse", parse_stock_location),
        accounting_code=str_field(data, "accounting_code"),
        export_status=str_field(data, "export_status"),
        export_date=datetime_field(data, "export_date"),
        export_message=str_or_none_field(data, "export_message"),
        tags=codes_field(data, "tags"),
        underlying_cost_amount=float_field(data, "underlying_cost_amount"),
        underlying_cost_amount_tax=float_field(data, "underlying_cost_amount_tax"),
        underlying_cost_amount_with_tax=float_field(data, "underlying_cost_amount_with_tax"),
        approved_by=link_field(data, "approved_by"),
        approved_at=datetime_field(data, "approved_at"),
        projects_json=str_or_none_field(data, "projects_json"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_purchase_order_cost(data: Mapping[str, Any]) -> PurchaseOrderCost:
    """Build the purchase order cost model from one cost line payload."""
    return PurchaseOrderCost(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        purchase_order=link_or_model_field(data, "purchase_order", parse_purchase_order)
        or RentmanLink(str_field(data, "purchase_order")),
        costitem=int_field(data, "costitem"),
        costitemtype=str_field(data, "costitemtype"),
        approved_amount=float_field(data, "approved_amount"),
        project=str_field(data, "project"),
        underlying_cost_amount=float_field(data, "underlying_cost_amount"),
        underlying_cost_amount_tax=float_field(data, "underlying_cost_amount_tax"),
        underlying_cost_amount_with_tax=float_field(data, "underlying_cost_amount_with_tax"),
        quantity=int_field(data, "quantity"),
        raw=dict(data),
    )


def parse_purchase_order_global_cost(data: Mapping[str, Any]) -> PurchaseOrderGlobalCost:
    """Build the global cost model from one global cost line payload."""
    return PurchaseOrderGlobalCost(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        purchase_order=link_or_model_field(data, "purchase_order", parse_purchase_order)
        or RentmanLink(str_field(data, "purchase_order")),
        name=str_field(data, "name"),
        unit_purchase_cost=float_field(data, "unit_purchase_cost"),
        quantity=int_field(data, "quantity"),
        taxclass=link_or_model_field(data, "taxclass", parse_tax_class),
        raw=dict(data),
    )


def parse_crew(data: Mapping[str, Any]) -> Crew:
    """Build the crew model from one crew member payload."""
    return Crew(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        folder=link_or_model_field(data, "folder", parse_folder),
        street=str_field(data, "street"),
        housenumber=str_field(data, "housenumber"),
        unit_number=str_field(data, "unit_number"),
        district=str_field(data, "district"),
        city=str_field(data, "city"),
        postal_code=str_field(data, "postal_code"),
        addressline2=str_field(data, "addressline2"),
        extraaddressline=str_field(data, "extraaddressline"),
        state=str_field(data, "state"),
        country=str_field(data, "country"),
        birthdate=datetime_field(data, "birthdate"),
        passport_number=str_field(data, "passport_number"),
        emergency_contact=str_field(data, "emergency_contact"),
        remark=str_field(data, "remark"),
        driving_license=str_field(data, "driving_license"),
        contract=coerced_str_field(data, "contract"),
        bank=str_field(data, "bank"),
        contract_date=datetime_field(data, "contract_date"),
        company_name=str_field(data, "company_name"),
        vat_code=str_field(data, "vat_code"),
        coc_code=str_field(data, "coc_code"),
        firstname=str_field(data, "firstname"),
        middle_name=str_field(data, "middle_name"),
        lastname=str_field(data, "lastname"),
        email=str_field(data, "email"),
        phone=str_field(data, "phone"),
        active=bool_field(data, "active"),
        avatar=link_field(data, "avatar"),
        vt_fullname=str_field(data, "vt_fullname"),
        default_warehouse=link_or_model_field(data, "default_warehouse", parse_stock_location),
        external_reference=str_field(data, "external_reference"),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_crew_availability(data: Mapping[str, Any]) -> CrewAvailability:
    """Build the availability model from one availability window payload."""
    return CrewAvailability(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        last_updater=link_field(data, "last_updater"),
        last_updated=datetime_field(data, "last_updated"),
        start=datetime_field(data, "start"),
        end=datetime_field(data, "end"),
        crewmember=link_or_model_field(data, "crewmember", parse_crew)
        or RentmanLink(str_field(data, "crewmember")),
        status=str_field(data, "status"),
        remark=str_field(data, "remark"),
        recurrence_interval_unit=str_field(data, "recurrence_interval_unit"),
        recurrence_enddate=datetime_field(data, "recurrence_enddate"),
        recurrence_interval=int_field(data, "recurrence_interval"),
        recurrent_group=int_field(data, "recurrent_group"),
        recurrence_weekdays=str_field(data, "recurrence_weekdays"),
        raw=dict(data),
    )


def parse_crew_rate(data: Mapping[str, Any]) -> CrewRate:
    """Build the crew rate model from one crew rate payload."""
    return CrewRate(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        naam=str_field(data, "naam"),
        cost_rate=link_field(data, "cost_rate"),
        medewerker=link_or_model_field(data, "medewerker", parse_crew)
        or RentmanLink(str_field(data, "medewerker")),
        raw=dict(data),
    )


def parse_appointment(data: Mapping[str, Any]) -> Appointment:
    """Build the appointment model from one appointment payload."""
    return Appointment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        start=datetime_field(data, "start"),
        end=datetime_field(data, "end"),
        color=str_field(data, "color"),
        location=str_field(data, "location"),
        remark=str_field(data, "remark"),
        is_public=bool_field(data, "is_public"),
        is_plannable=bool_field(data, "is_plannable"),
        recurrence_interval_unit=str_field(data, "recurrence_interval_unit"),
        recurrence_enddate=datetime_field(data, "recurrence_enddate"),
        recurrence_interval=int_field(data, "recurrence_interval"),
        recurrence_group=int_field(data, "recurrence_group"),
        recurrence_weekdays=str_or_none_field(data, "recurrence_weekdays"),
        synchronization_id=str_field(data, "synchronization_id"),
        synchronisation_uri=str_field(data, "synchronisation_uri"),
        raw=dict(data),
    )


def parse_appointment_crew(data: Mapping[str, Any]) -> AppointmentCrew:
    """Build the appointment crew model from one attachment payload."""
    return AppointmentCrew(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        appointment=link_or_model_field(data, "appointment", parse_appointment)
        or RentmanLink(str_field(data, "appointment")),
        crew=link_or_model_field(data, "crew", parse_crew) or RentmanLink(str_field(data, "crew")),
        raw=dict(data),
    )


def parse_invitation(data: Mapping[str, Any]) -> Invitation:
    """Build the invitation model from one planning invitation payload."""
    return Invitation(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        type=str_field(data, "type"),
        accepted=bool_field(data, "accepted"),
        responded_timestamp=datetime_field(data, "responded_timestamp"),
        expiration_date=datetime_field(data, "expiration_date"),
        start=datetime_field(data, "start"),
        end=datetime_field(data, "end"),
        function=link_field(data, "function"),
        projectcrew=link_field(data, "projectcrew"),
        crewmember=link_or_model_field(data, "crewmember", parse_crew)
        or RentmanLink(str_field(data, "crewmember")),
        remark=str_field(data, "remark"),
        emailstatus=str_field(data, "emailstatus"),
        last_reminder=datetime_field(data, "last_reminder"),
        location_details=str_or_none_field(data, "location_details"),
        auto_reminder_date=datetime_field(data, "auto_reminder_date"),
        auto_reminder_sent=int_field(data, "auto_reminder_sent"),
        raw=dict(data),
    )


def parse_leave_type(data: Mapping[str, Any]) -> LeaveType:
    """Build the leave type model from one leave type payload."""
    return LeaveType(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        type=str_field(data, "type"),
        name=str_field(data, "name"),
        payroll_code=str_field(data, "payroll_code"),
        color=str_field(data, "color"),
        requires_approval=bool_field(data, "requires_approval"),
        affects_availability=bool_field(data, "affects_availability"),
        has_balance=bool_field(data, "has_balance"),
        balance_start_date=datetime_field(data, "balance_start_date"),
        is_labor=str_field(data, "is_labor"),
        has_calculated_duration=bool_field(data, "has_calculated_duration"),
        can_have_activities=bool_field(data, "can_have_activities"),
        counts_in_totals=bool_field(data, "counts_in_totals"),
        raw=dict(data),
    )


def parse_leave_request(data: Mapping[str, Any]) -> LeaveRequest:
    """Build the leave request model from one leave request payload."""
    return LeaveRequest(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        description=str_field(data, "description"),
        approval_status=str_field(data, "approval_status"),
        requested_for=link_or_model_field(data, "requested_for", parse_crew)
        or RentmanLink(str_field(data, "requested_for")),
        reviewed_on=datetime_field(data, "reviewed_on"),
        reviewer=link_field(data, "reviewer"),
        raw=dict(data),
    )


def parse_leave_mutation(data: Mapping[str, Any]) -> LeaveMutation:
    """Build the leave mutation model from one balance mutation payload."""
    return LeaveMutation(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        description=str_field(data, "description"),
        duration=float_field(data, "duration"),
        crewmember=link_or_model_field(data, "crewmember", parse_crew)
        or RentmanLink(str_field(data, "crewmember")),
        leavetype=link_or_model_field(data, "leavetype", parse_leave_type)
        or RentmanLink(str_field(data, "leavetype")),
        mutation_date=datetime_field(data, "mutation_date"),
        raw=dict(data),
    )


def parse_time_registration(data: Mapping[str, Any]) -> TimeRegistration:
    """Build the time registration model from one registration payload."""
    return TimeRegistration(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        crewmember=link_or_model_field(data, "crewmember", parse_crew),
        start=datetime_field(data, "start"),
        end=datetime_field(data, "end"),
        distance=float_field(data, "distance"),
        is_lunch_included=bool_field(data, "is_lunch_included"),
        leavetype=link_or_model_field(data, "leavetype", parse_leave_type),
        leaverequest=link_or_model_field(data, "leaverequest", parse_leave_request),
        duration=float_field(data, "duration"),
        break_duration=float_field(data, "break_duration"),
        travel_time=float_field(data, "travel_time"),
        correction_duration=float_field(data, "correction_duration"),
        remark=str_field(data, "remark"),
        status=str_field(data, "status"),
        break_duration_with_start_end=float_field(data, "break_duration_with_start_end"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_time_registration_activity(data: Mapping[str, Any]) -> TimeRegistrationActivity:
    """Build the activity model from one activity line payload."""
    return TimeRegistrationActivity(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        time_registration=link_or_model_field(data, "time_registration", parse_time_registration)
        or RentmanLink(str_field(data, "time_registration")),
        project_function=link_or_model_field(data, "project_function", parse_project_function),
        subproject_function=link_or_model_field(
            data, "subproject_function", parse_project_function
        ),
        description=str_field(data, "description"),
        duration=float_field(data, "duration"),
        is_activity=bool_field(data, "is_activity"),
        from_=datetime_field(data, "from"),
        to=datetime_field(data, "to"),
        raw=dict(data),
    )


def parse_contact(data: Mapping[str, Any]) -> Contact:
    """Build the contact model from one contact payload."""
    return Contact(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        folder=link_or_model_field(data, "folder", parse_folder),
        type=str_field(data, "type"),
        ext_name_line=str_field(data, "ext_name_line"),
        firstname=str_field(data, "firstname"),
        distance=float_field(data, "distance"),
        travel_time=float_field(data, "travel_time"),
        surfix=str_field(data, "surfix"),
        surname=str_field(data, "surname"),
        longitude=float_field(data, "longitude"),
        latitude=float_field(data, "latitude"),
        code=str_field(data, "code"),
        accounting_code=str_field(data, "accounting_code"),
        vendor_accounting_code=str_field(data, "vendor_accounting_code"),
        name=str_field(data, "name"),
        gender=str_field(data, "gender"),
        mailing_city=str_field(data, "mailing_city"),
        mailing_street=str_field(data, "mailing_street"),
        mailing_number=str_field(data, "mailing_number"),
        mailing_unit_number=str_field(data, "mailing_unit_number"),
        mailing_district=str_field(data, "mailing_district"),
        mailing_extra_address_line=str_field(data, "mailing_extra_address_line"),
        mailing_postalcode=str_field(data, "mailing_postalcode"),
        mailing_state=str_field(data, "mailing_state"),
        mailing_country=str_field(data, "mailing_country"),
        visit_city=str_field(data, "visit_city"),
        visit_street=str_field(data, "visit_street"),
        visit_number=str_field(data, "visit_number"),
        visit_unit_number=str_field(data, "visit_unit_number"),
        visit_district=str_field(data, "visit_district"),
        visit_extra_address_line=str_field(data, "visit_extra_address_line"),
        visit_postalcode=str_field(data, "visit_postalcode"),
        visit_state=str_field(data, "visit_state"),
        country=str_field(data, "country"),
        invoice_city=str_field(data, "invoice_city"),
        invoice_street=str_field(data, "invoice_street"),
        invoice_number=str_field(data, "invoice_number"),
        invoice_unit_number=str_field(data, "invoice_unit_number"),
        invoice_district=str_field(data, "invoice_district"),
        invoice_extra_address_line=str_field(data, "invoice_extra_address_line"),
        invoice_postalcode=str_field(data, "invoice_postalcode"),
        invoice_state=str_field(data, "invoice_state"),
        invoice_country=str_field(data, "invoice_country"),
        phone_1=str_field(data, "phone_1"),
        phone_2=str_field(data, "phone_2"),
        email_1=str_field(data, "email_1"),
        email_2=str_field(data, "email_2"),
        website=str_field(data, "website"),
        VAT_code=str_field(data, "VAT_code"),
        fiscal_code=str_field(data, "fiscal_code"),
        commerce_code=str_field(data, "commerce_code"),
        purchase_number=str_field(data, "purchase_number"),
        bic=str_field(data, "bic"),
        bank_account=str_field(data, "bank_account"),
        default_person=link_or_model_field(data, "default_person", parse_contact_person),
        admin_contactperson=link_field(data, "admin_contactperson"),
        discount_crew=float_field(data, "discount_crew"),
        discount_transport=float_field(data, "discount_transport"),
        discount_rental=float_field(data, "discount_rental"),
        discount_sale=float_field(data, "discount_sale"),
        discount_total=float_field(data, "discount_total"),
        projectnote=str_field(data, "projectnote"),
        projectnote_title=str_field(data, "projectnote_title"),
        contact_warning=str_field(data, "contact_warning"),
        discount_subrent=float_field(data, "discount_subrent"),
        image=link_field(data, "image"),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_contact_person(data: Mapping[str, Any]) -> ContactPerson:
    """Build the contact person model from one contact person payload."""
    return ContactPerson(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        contact=link_or_model_field(data, "contact", parse_contact)
        or RentmanLink(str_field(data, "contact")),
        firstname=str_field(data, "firstname"),
        middle_name=str_field(data, "middle_name"),
        lastname=str_field(data, "lastname"),
        function=str_field(data, "function"),
        phone=str_field(data, "phone"),
        street=str_field(data, "street"),
        number=str_field(data, "number"),
        postalcode=str_field(data, "postalcode"),
        city=str_field(data, "city"),
        state=str_field(data, "state"),
        country=str_field(data, "country"),
        mobilephone=str_field(data, "mobilephone"),
        email=str_field(data, "email"),
        tags=codes_field(data, "tags"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_task_status(data: Mapping[str, Any]) -> TaskStatus:
    """Build the task status model from one status payload."""
    return TaskStatus(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        color=str_field(data, "color"),
        type=str_field(data, "type"),
        order=coerced_str_field(data, "order"),
        raw=dict(data),
    )


def parse_task(data: Mapping[str, Any]) -> Task:
    """Build the task model from one task payload."""
    return Task(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        recurhoe=str_field(data, "recurhoe"),
        recureind=str_or_none_field(data, "recureind"),
        recurperiode=int_field(data, "recurperiode"),
        is_template=bool_field(data, "is_template"),
        name=str_field(data, "name"),
        details=str_field(data, "details"),
        color=str_field(data, "color"),
        priority=str_field(data, "priority"),
        order=coerced_str_field(data, "order"),
        deadline=datetime_field(data, "deadline"),
        deadline_type=str_field(data, "deadline_type"),
        deadline_relative_offset_base=str_field(data, "deadline_relative_offset_base"),
        deadline_relative_offset_amount=int_field(data, "deadline_relative_offset_amount"),
        deadline_relative_offset_unit=str_field(data, "deadline_relative_offset_unit"),
        deadline_relative_offset_direction=str_field(data, "deadline_relative_offset_direction"),
        completed_at=datetime_field(data, "completed_at"),
        status=link_or_model_field(data, "status", parse_task_status)
        or RentmanLink(str_field(data, "status")),
        item=int_field(data, "item"),
        itemtype=str_or_none_field(data, "itemtype"),
        synchronization_id=str_field(data, "synchronization_id"),
        synchronization_uri=str_field(data, "synchronization_uri"),
        public=coerced_str_field(data, "public"),
        assignment_type=str_field(data, "assignment_type"),
        completed_by=link_field(data, "completed_by"),
        expiry_notification_date=datetime_field(data, "expiry_notification_date"),
        time_budget=float_field(data, "time_budget"),
        tags=codes_field(data, "tags"),
        parent_api_path=str_field(data, "parent_api_path"),
        custom=custom_field(data),
        raw=dict(data),
    )


def parse_subtask(data: Mapping[str, Any]) -> Subtask:
    """Build the subtask model from one checklist line payload."""
    return Subtask(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        task=link_or_model_field(data, "task", parse_task) or RentmanLink(str_field(data, "task")),
        title=str_field(data, "title"),
        completed=bool_field(data, "completed"),
        raw=dict(data),
    )


def parse_task_assignment(data: Mapping[str, Any]) -> TaskAssignment:
    """Build the task assignment model from one assignment payload."""
    return TaskAssignment(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        task=link_or_model_field(data, "task", parse_task) or RentmanLink(str_field(data, "task")),
        crew=link_or_model_field(data, "crew", parse_crew) or RentmanLink(str_field(data, "crew")),
        raw=dict(data),
    )


def parse_file_folder(data: Mapping[str, Any]) -> FileFolder:
    """Build the file folder model from one folder payload."""
    return FileFolder(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        parent=link_or_model_field(data, "parent", parse_file_folder),
        name=str_field(data, "name"),
        classified=bool_field(data, "classified"),
        item=int_field(data, "item"),
        itemtype=str_or_none_field(data, "itemtype"),
        is_template=bool_field(data, "is_template"),
        parent_api_path=str_field(data, "parent_api_path"),
        raw=dict(data),
    )


def parse_file(data: Mapping[str, Any]) -> File:
    """Build the file model from one stored file payload."""
    return File(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        readable_name=str_field(data, "readable_name"),
        expiration=datetime_field(data, "expiration"),
        size=int_field(data, "size"),
        image=bool_field(data, "image"),
        item=int_field(data, "item"),
        itemtype=str_or_none_field(data, "itemtype"),
        description=str_field(data, "description"),
        in_documents=bool_field(data, "in_documents"),
        in_webshop=bool_field(data, "in_webshop"),
        classified=bool_field(data, "classified"),
        public=bool_field(data, "public"),
        type=str_field(data, "type"),
        preview_of=link_field(data, "preview_of"),
        previewstatus=str_field(data, "previewstatus"),
        file_item=int_field(data, "file_item"),
        file_itemtype=str_field(data, "file_itemtype"),
        folder=link_or_model_field(data, "folder", parse_file_folder),
        path=str_field(data, "path"),
        path_without_file_name=str_field(data, "path_without_file_name"),
        path_with_file_folders=str_field(data, "path_with_file_folders"),
        name_without_extension=str_field(data, "name_without_extension"),
        friendly_name_without_extension=str_field(data, "friendly_name_without_extension"),
        extension=str_field(data, "extension"),
        url=str_field(data, "url"),
        proxy_url=str_field(data, "proxy_url"),
        parent_api_path=str_field(data, "parent_api_path"),
        raw=dict(data),
    )


def parse_rate(data: Mapping[str, Any]) -> Rate:
    """Build the rate model from one rate definition payload."""
    return Rate(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        archived=bool_field(data, "archived"),
        type=str_field(data, "type"),
        subtype=str_field(data, "subtype"),
        raw=dict(data),
    )


def parse_rate_factor(data: Mapping[str, Any]) -> RateFactor:
    """Build the rate factor model from one rate bracket payload."""
    return RateFactor(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        rate_id=link_or_model_field(data, "rate_id", parse_rate)
        or RentmanLink(str_field(data, "rate_id")),
        from_=float_field(data, "from"),
        to=float_field(data, "to"),
        variable=float_field(data, "variable"),
        fixed=float_field(data, "fixed"),
        raw=dict(data),
    )


def parse_factor_group(data: Mapping[str, Any]) -> FactorGroup:
    """Build the factor group model from one group payload."""
    return FactorGroup(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        name=str_field(data, "name"),
        raw=dict(data),
    )


def parse_factor(data: Mapping[str, Any]) -> Factor:
    """Build the factor model from one day bracket payload."""
    return Factor(
        id=required_id(data),
        created=datetime_field(data, "created"),
        modified=datetime_field(data, "modified"),
        update_hash=str_field(data, "updateHash"),
        creator=link_field(data, "creator"),
        displayname=str_field(data, "displayname"),
        from_days=int_field(data, "from_days"),
        to_days=int_field(data, "to_days"),
        factor=coerced_str_field(data, "factor"),
        factor_group=link_or_model_field(data, "factor_group", parse_factor_group)
        or RentmanLink(str_field(data, "factor_group")),
        raw=dict(data),
    )
